#!/bin/sh

home=$HOME
cwd=$(pwd)
bin=$HOME/bin
utils=$cmd/utils
plugm=$home/.vim/autoload/plug.vim

ln -sf $cwd/_vimrc $home/.vimrc
if [ ! -f $plugm ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -c "PlugInstall" +"qall"

if [ ! -d $bin ]; then
    mkdir $bin
fi

echo "Installing utilities to $bin..."
for file in `ls $utils`
do
    ln -sf $utils/$file $bin/$file
done
echo "Done." 

exit 0
